# Azure ML workspace configuration
workspace:
  subscription_id: "146253af-8dff-4ab7-b56f-c2bf8f847a24"  # Your actual subscription ID
  resource_group: "aakash-trial"                    # Replace with your resource group name
  name: "iris-dataset"                              # Replace with your Azure ML workspace name
  location: "central india"                                       # Azure region

# Compute configuration
compute:
  name: "ml-training-cluster"
  vm_size: "Standard_DS3_v2"               # VM size for training
  min_instances: 0
  max_instances: 1

# Environment configuration
environment:
  name: "iris-training-env"
  description: "Environment for Iris classification training"
  conda_file: "config/conda-env.yml"

# Experiment configuration
experiment:
  name: "iris-classification"
  description: "Iris species classification experiment"